services:
  - type: web
    name: ds
    runtime: node
    plan: standard
    autoDeploy: true
    buildCommand: bun install && bun run build
    startCommand: bun migrate && bun start
    envVars:
      - fromGroup: ds/servers
      - key: DATABASE_URL
        fromDatabase:
          name: ds
          property: connectionString
databases:
  - name: ds
    user: admin
    plan: basic-256mb